site_name: Groundhog all the way north
theme:
  name: material
  language: zh
  palette:
    primary: black
  features:
    - navigation.close
  favicon: assets/avatar-img.png
  logo: assets/avatar-img.png
  hide: true
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Devops:
      - Registry:
          - Artifactory: devops/registry/artifactory.md
          - Harbor: ""
      - CI:
          - Github Action:
              - Runtime:
                  - K8s: devops/ci/github_action/runtime/kubernetes_runner.md
                  - Cloud: devops/ci/github_action/runtime/runner_on_ecs.md
              - Action Development:
                  - TS action: devops/ci/github_action/actions/action_ts.md
                  - Docker action: devops/ci/github_action/actions/action_docker.md
          - Tekton: ""
      - CD:
          - ArgoCD: ""
          - Flux: ""
  - Public Cloud:
      - Alibaba Cloud:
          - Ingress deployment: public-cloud/alicloud_ingress.md
      - AWS: public-cloud/index.md
      - Azure: public-cloud/index.md
  - Kubernetes:
      - HPA: kubernetes/knowledge/hpa.md
      - Resource limit:
          - CPU: kubernetes/knowledge/cpu_limit.md
      - Monitoring:
          - Solutions: kubernetes/monitor/solutions.md
          - Alarm: kubernetes/monitor/alert.md
          - Metrics: kubernetes/monitor/metrics.md
      - Operator: kubernetes/operator/index.md
  - Others:
      - Tools:
          - MKDocs: tools/mkdoc.md
          - Plantuml with vscode: tools/plantuml_vscode.md
          - MacOS: tools/macos.md

extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
